// <auto-generated />
namespace ArmyClient.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class start_test : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(start_test));
        
        string IMigrationMetadata.Id
        {
            get { return "201912191847134_start_test"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
