// <auto-generated />
namespace ArmyClient.Migrations.MSSQL
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class RemoveRequiredWebAdressOnForgnFriends2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RemoveRequiredWebAdressOnForgnFriends2));
        
        string IMigrationMetadata.Id
        {
            get { return "202001070805228_RemoveRequiredWebAdressOnForgnFriends2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
