// <auto-generated />
namespace ArmyClient.Migrations.PostgreSQL
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class pg_1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(pg_1));
        
        string IMigrationMetadata.Id
        {
            get { return "202001051217133_pg_1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
